name: VEP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - joblib=1.4.2
  - h5py=3.11
  - pandas=2.2.2
  - numpy=1.26.4
  # - pip
  # - pip:
  #     - fair-esm
  #     - pysam==0.22.1
  #     - transvar
  #     - bgzip

